import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { type SanityDocument } from "next-sanity";
import { client } from "@/sanity/client";
import "./globals.css";
import "@/styles/main.scss";

const ABOUT_QUERY = `*[_type == "about"][0]{
  title,
  slug,
  publishedAt,
  name,
  headline,
  email,
  github,
  linkedin,
  phone,
  image,
  bio,
}`;

const options = { next: { revalidate: 30 } };

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const aboutInfo = await client.fetch<SanityDocument>(
    ABOUT_QUERY,
    {},
    options
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="nav-container">
          <nav className="container mx-auto p-8">
            <ul>
              <li>
                <Link href={`/`}>Home</Link>
              </li>
              <li>{pathname != "/" && <Link href={`#about`}>About</Link>}</li>
              <li>
                {pathname != "/" && <Link href={`#projects`}>Projects</Link>}
              </li>
              <li>
                <Link href={`#contact`}>Contact</Link>
              </li>
            </ul>
          </nav>
        </div>
        {children}
        <div className="footer-container">
          <footer id="contact" className="container mx-auto p-8">
            <p>
              <Link
                href={`mailto:${aboutInfo.email}`}
                aria-label="Email link"
                target="_blank"
              >
                Email
              </Link>
            </p>
            <p>
              <Link
                href={aboutInfo.github}
                aria-label="Github link"
                target="_blank"
              >
                Github
              </Link>
            </p>
            <p>
              <Link
                href={aboutInfo.linkedin}
                aria-label="LinkedIn link"
                target="_blank"
              >
                LinkedIn
              </Link>
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
